// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_axis_fpga_sha256_digester (
        ap_clk,
        ap_rst,
        k,
        rx_state,
        rx_w,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] k;
input  [255:0] rx_state;
input  [511:0] rx_w;
output  [767:0] ap_return;
input   ap_ce;

wire   [31:0] ret_V_fu_272_p2;
reg   [31:0] ret_V_reg_815;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] ret_V_10_fu_460_p2;
reg   [31:0] ret_V_10_reg_820;
wire   [31:0] t1_V_fu_722_p2;
reg   [31:0] t1_V_reg_825;
wire   [31:0] new_w_V_fu_750_p2;
reg   [31:0] new_w_V_reg_831;
reg   [479:0] tmp_22_reg_836;
reg   [31:0] tmp_23_reg_841;
reg   [95:0] tmp_24_reg_846;
wire   [95:0] trunc_ln312_fu_786_p1;
reg   [95:0] trunc_ln312_reg_851;
wire    ap_block_pp0_stage0;
wire   [1:0] trunc_ln674_fu_210_p1;
wire   [29:0] tmp_fu_200_p4;
wire   [12:0] trunc_ln674_1_fu_232_p1;
wire   [18:0] tmp_5_fu_222_p4;
wire   [21:0] trunc_ln674_2_fu_254_p1;
wire   [9:0] tmp_7_fu_244_p4;
wire   [31:0] temp0_V_fu_214_p3;
wire   [31:0] temp2_V_fu_258_p3;
wire   [31:0] xor_ln1545_fu_266_p2;
wire   [31:0] temp1_V_fu_236_p3;
wire   [5:0] tmp_1_fu_298_p4;
wire   [25:0] tmp_9_fu_288_p4;
wire   [10:0] tmp_3_fu_326_p4;
wire   [20:0] tmp_2_fu_316_p4;
wire   [24:0] tmp_s_fu_354_p4;
wire   [6:0] tmp_4_fu_344_p4;
wire   [31:0] temp0_V_1_fu_308_p3;
wire   [31:0] temp2_V_1_fu_364_p3;
wire   [31:0] xor_ln1545_2_fu_372_p2;
wire   [31:0] temp1_V_1_fu_336_p3;
wire   [31:0] z_V_fu_394_p4;
wire   [31:0] y_V_fu_384_p4;
wire   [31:0] ret_V_4_fu_404_p2;
wire   [31:0] x_V_1_fu_278_p4;
wire   [31:0] ret_V_5_fu_410_p2;
wire   [31:0] y_V_1_fu_422_p4;
wire   [31:0] x_V_fu_196_p1;
wire   [31:0] z_V_1_fu_432_p4;
wire   [31:0] ret_V_8_fu_448_p2;
wire   [31:0] ret_V_9_fu_454_p2;
wire   [31:0] ret_V_7_fu_442_p2;
wire   [2:0] tmp_8_fu_476_p4;
wire   [2:0] tmp_6_fu_466_p4;
wire   [3:0] tmp_11_fu_502_p4;
wire   [24:0] tmp_10_fu_492_p4;
wire   [14:0] tmp_13_fu_530_p4;
wire   [13:0] tmp_12_fu_520_p4;
wire   [28:0] temp1_V_2_fu_512_p3;
wire   [28:0] temp3_V_fu_548_p4;
wire   [28:0] xor_ln1545_7_fu_558_p2;
wire   [28:0] temp2_V_2_fu_540_p3;
wire   [2:0] temp0_V_2_fu_486_p2;
wire   [28:0] ret_V_11_fu_564_p2;
wire   [9:0] tmp_15_fu_588_p4;
wire   [9:0] tmp_14_fu_578_p4;
wire   [6:0] tmp_17_fu_614_p4;
wire   [14:0] tmp_16_fu_604_p4;
wire   [8:0] tmp_19_fu_642_p4;
wire   [12:0] tmp_18_fu_632_p4;
wire   [21:0] temp1_V_3_fu_624_p3;
wire   [21:0] temp3_V_1_fu_660_p4;
wire   [21:0] xor_ln1545_10_fu_670_p2;
wire   [21:0] temp2_V_3_fu_652_p3;
wire   [9:0] temp0_V_3_fu_598_p2;
wire   [21:0] ret_V_12_fu_676_p2;
wire   [31:0] tmp_20_fu_690_p4;
wire   [31:0] trunc_ln674_3_fu_700_p1;
wire   [31:0] ret_V_6_fu_416_p2;
wire   [31:0] add_ln232_1_fu_710_p2;
wire   [31:0] ret_V_3_fu_378_p2;
wire   [31:0] add_ln232_2_fu_716_p2;
wire   [31:0] add_ln232_fu_704_p2;
wire   [31:0] p_Result_1_fu_682_p3;
wire   [31:0] p_Result_s_fu_570_p3;
wire   [31:0] tmp_21_fu_728_p4;
wire   [31:0] add_ln232_5_fu_744_p2;
wire   [31:0] add_ln232_4_fu_738_p2;
wire   [31:0] add_ln414_9_fu_794_p2;
wire   [31:0] add_ln414_fu_790_p2;
wire   [31:0] add_ln414_8_fu_798_p2;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        new_w_V_reg_831 <= new_w_V_fu_750_p2;
        ret_V_10_reg_820 <= ret_V_10_fu_460_p2;
        ret_V_reg_815 <= ret_V_fu_272_p2;
        t1_V_reg_825 <= t1_V_fu_722_p2;
        tmp_22_reg_836 <= {{rx_w[511:32]}};
        tmp_23_reg_841 <= {{rx_state[127:96]}};
        tmp_24_reg_846 <= {{rx_state[223:128]}};
        trunc_ln312_reg_851 <= trunc_ln312_fu_786_p1;
    end
end

assign add_ln232_1_fu_710_p2 = (ret_V_6_fu_416_p2 + k);

assign add_ln232_2_fu_716_p2 = (add_ln232_1_fu_710_p2 + ret_V_3_fu_378_p2);

assign add_ln232_4_fu_738_p2 = (p_Result_1_fu_682_p3 + p_Result_s_fu_570_p3);

assign add_ln232_5_fu_744_p2 = (trunc_ln674_3_fu_700_p1 + tmp_21_fu_728_p4);

assign add_ln232_fu_704_p2 = (tmp_20_fu_690_p4 + trunc_ln674_3_fu_700_p1);

assign add_ln414_8_fu_798_p2 = (add_ln414_9_fu_794_p2 + ret_V_10_reg_820);

assign add_ln414_9_fu_794_p2 = (ret_V_reg_815 + t1_V_reg_825);

assign add_ln414_fu_790_p2 = (tmp_23_reg_841 + t1_V_reg_825);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return = {{{{{{tmp_24_reg_846}, {add_ln414_fu_790_p2}}, {trunc_ln312_reg_851}}, {add_ln414_8_fu_798_p2}}, {new_w_V_reg_831}}, {tmp_22_reg_836}};

assign new_w_V_fu_750_p2 = (add_ln232_5_fu_744_p2 + add_ln232_4_fu_738_p2);

assign p_Result_1_fu_682_p3 = {{temp0_V_3_fu_598_p2}, {ret_V_12_fu_676_p2}};

assign p_Result_s_fu_570_p3 = {{temp0_V_2_fu_486_p2}, {ret_V_11_fu_564_p2}};

assign ret_V_10_fu_460_p2 = (ret_V_9_fu_454_p2 | ret_V_7_fu_442_p2);

assign ret_V_11_fu_564_p2 = (xor_ln1545_7_fu_558_p2 ^ temp2_V_2_fu_540_p3);

assign ret_V_12_fu_676_p2 = (xor_ln1545_10_fu_670_p2 ^ temp2_V_3_fu_652_p3);

assign ret_V_3_fu_378_p2 = (xor_ln1545_2_fu_372_p2 ^ temp1_V_1_fu_336_p3);

assign ret_V_4_fu_404_p2 = (z_V_fu_394_p4 ^ y_V_fu_384_p4);

assign ret_V_5_fu_410_p2 = (x_V_1_fu_278_p4 & ret_V_4_fu_404_p2);

assign ret_V_6_fu_416_p2 = (z_V_fu_394_p4 ^ ret_V_5_fu_410_p2);

assign ret_V_7_fu_442_p2 = (y_V_1_fu_422_p4 & x_V_fu_196_p1);

assign ret_V_8_fu_448_p2 = (y_V_1_fu_422_p4 | x_V_fu_196_p1);

assign ret_V_9_fu_454_p2 = (z_V_1_fu_432_p4 & ret_V_8_fu_448_p2);

assign ret_V_fu_272_p2 = (xor_ln1545_fu_266_p2 ^ temp1_V_fu_236_p3);

assign t1_V_fu_722_p2 = (add_ln232_2_fu_716_p2 + add_ln232_fu_704_p2);

assign temp0_V_1_fu_308_p3 = {{tmp_1_fu_298_p4}, {tmp_9_fu_288_p4}};

assign temp0_V_2_fu_486_p2 = (tmp_8_fu_476_p4 ^ tmp_6_fu_466_p4);

assign temp0_V_3_fu_598_p2 = (tmp_15_fu_588_p4 ^ tmp_14_fu_578_p4);

assign temp0_V_fu_214_p3 = {{trunc_ln674_fu_210_p1}, {tmp_fu_200_p4}};

assign temp1_V_1_fu_336_p3 = {{tmp_3_fu_326_p4}, {tmp_2_fu_316_p4}};

assign temp1_V_2_fu_512_p3 = {{tmp_11_fu_502_p4}, {tmp_10_fu_492_p4}};

assign temp1_V_3_fu_624_p3 = {{tmp_17_fu_614_p4}, {tmp_16_fu_604_p4}};

assign temp1_V_fu_236_p3 = {{trunc_ln674_1_fu_232_p1}, {tmp_5_fu_222_p4}};

assign temp2_V_1_fu_364_p3 = {{tmp_s_fu_354_p4}, {tmp_4_fu_344_p4}};

assign temp2_V_2_fu_540_p3 = {{tmp_13_fu_530_p4}, {tmp_12_fu_520_p4}};

assign temp2_V_3_fu_652_p3 = {{tmp_19_fu_642_p4}, {tmp_18_fu_632_p4}};

assign temp2_V_fu_258_p3 = {{trunc_ln674_2_fu_254_p1}, {tmp_7_fu_244_p4}};

assign temp3_V_1_fu_660_p4 = {{rx_w[479:458]}};

assign temp3_V_fu_548_p4 = {{rx_w[63:35]}};

assign tmp_10_fu_492_p4 = {{rx_w[63:39]}};

assign tmp_11_fu_502_p4 = {{rx_w[35:32]}};

assign tmp_12_fu_520_p4 = {{rx_w[63:50]}};

assign tmp_13_fu_530_p4 = {{rx_w[46:32]}};

assign tmp_14_fu_578_p4 = {{rx_w[464:455]}};

assign tmp_15_fu_588_p4 = {{rx_w[466:457]}};

assign tmp_16_fu_604_p4 = {{rx_w[479:465]}};

assign tmp_17_fu_614_p4 = {{rx_w[454:448]}};

assign tmp_18_fu_632_p4 = {{rx_w[479:467]}};

assign tmp_19_fu_642_p4 = {{rx_w[456:448]}};

assign tmp_1_fu_298_p4 = {{rx_state[133:128]}};

assign tmp_20_fu_690_p4 = {{rx_state[255:224]}};

assign tmp_21_fu_728_p4 = {{rx_w[319:288]}};

assign tmp_2_fu_316_p4 = {{rx_state[159:139]}};

assign tmp_3_fu_326_p4 = {{rx_state[138:128]}};

assign tmp_4_fu_344_p4 = {{rx_state[159:153]}};

assign tmp_5_fu_222_p4 = {{rx_state[31:13]}};

assign tmp_6_fu_466_p4 = {{rx_w[38:36]}};

assign tmp_7_fu_244_p4 = {{rx_state[31:22]}};

assign tmp_8_fu_476_p4 = {{rx_w[49:47]}};

assign tmp_9_fu_288_p4 = {{rx_state[159:134]}};

assign tmp_fu_200_p4 = {{rx_state[31:2]}};

assign tmp_s_fu_354_p4 = {{rx_state[152:128]}};

assign trunc_ln312_fu_786_p1 = rx_state[95:0];

assign trunc_ln674_1_fu_232_p1 = rx_state[12:0];

assign trunc_ln674_2_fu_254_p1 = rx_state[21:0];

assign trunc_ln674_3_fu_700_p1 = rx_w[31:0];

assign trunc_ln674_fu_210_p1 = rx_state[1:0];

assign x_V_1_fu_278_p4 = {{rx_state[159:128]}};

assign x_V_fu_196_p1 = rx_state[31:0];

assign xor_ln1545_10_fu_670_p2 = (temp3_V_1_fu_660_p4 ^ temp1_V_3_fu_624_p3);

assign xor_ln1545_2_fu_372_p2 = (temp2_V_1_fu_364_p3 ^ temp0_V_1_fu_308_p3);

assign xor_ln1545_7_fu_558_p2 = (temp3_V_fu_548_p4 ^ temp1_V_2_fu_512_p3);

assign xor_ln1545_fu_266_p2 = (temp2_V_fu_258_p3 ^ temp0_V_fu_214_p3);

assign y_V_1_fu_422_p4 = {{rx_state[63:32]}};

assign y_V_fu_384_p4 = {{rx_state[191:160]}};

assign z_V_1_fu_432_p4 = {{rx_state[95:64]}};

assign z_V_fu_394_p4 = {{rx_state[223:192]}};

endmodule //sha256_axis_fpga_sha256_digester
